import {
    WebSocketGateway,
    WebSocketServer,
    OnGatewayConnection,
    OnGatewayDisconnect,
    SubscribeMessage,
    MessageBody,
    ConnectedSocket,
} from '@nestjs/websockets';
import { Server, Socket } from 'socket.io';
import { Injectable, Logger } from '@nestjs/common';
import { RiskScoreHistory } from '../entities/risk-score-history.entity';
import { RiskEvent } from '../entities/risk-event.entity';

@Injectable()
@WebSocketGateway({
    cors: {
        origin: '*', // Customize to frontend URL in production
    },
})
export class RiskGateway implements OnGatewayConnection, OnGatewayDisconnect {
    @WebSocketServer()
    server: Server;

    private readonly logger = new Logger(RiskGateway.name);

    handleConnection(client: Socket) {
        this.logger.log(`Client connected: ${client.id}`);
    }

    handleDisconnect(client: Socket) {
        this.logger.log(`Client disconnected: ${client.id}`);
    }

    @SubscribeMessage('join_company_room')
    handleJoinRoom(
        @MessageBody() data: { companyId: string },
        @ConnectedSocket() client: Socket,
    ) {
        if (data.companyId) {
            client.join(data.companyId);
            this.logger.log(`Client ${client.id} joined room: ${data.companyId}`);
            return { status: 'joined', room: data.companyId };
        }
        return { status: 'error', message: 'companyId is required' };
    }

    /**
     * Emits a real-time risk update to all clients connected to the company's room.
     * @param companyId The ID of the company
     * @param newHistory The newly generated RiskScoreHistory record
     * @param newAlert The RiskEvent or summary generated by the AI
     */
    emitRiskUpdate(companyId: string, newHistory: RiskScoreHistory, newAlert: RiskEvent) {
        this.logger.log(`Emitting risk update for company: ${companyId}`);
        this.server.to(companyId).emit('new_risk_update', {
            newScore: {
                id: newHistory.id,
                companyId: newHistory.companyId,
                period: newHistory.createdAt.toISOString(),
                totalScore: newHistory.totalDynamicScore,
                profitabilityScore: newHistory.baseFinancialScore,
                createdAt: newHistory.createdAt.toISOString()
            },
            newAlert: {
                id: newAlert.id,
                companyId: newAlert.companyId,
                severity: newAlert.riskScoreValue > 70 ? 'HIGH' : 'MEDIUM',
                message: newAlert.summary,
                createdAt: newAlert.publishedAt.toISOString(),
                isResolved: false
            }
        });
    }
}
